import type { Contact, IncomingMessage } from "./types";

export const directory: Contact[] = [
  {
    id: "c-owner-1",
    name: "فهد العتيبي",
    phone: "+966501111001",
    role: "owner",
  },
  {
    id: "c-owner-2",
    name: "نورة الشمري",
    phone: "+966501111002",
    role: "owner",
  },
  {
    id: "c-customer-1",
    name: "سارة القحطاني",
    phone: "+966502222001",
    role: "customer",
  },
  {
    id: "c-customer-2",
    name: "عبدالله الحربي",
    phone: "+966502222002",
    role: "customer",
  },
  {
    id: "c-agent-1",
    name: "مكتب النخبة",
    phone: "+966503333001",
    role: "agent",
  },
  {
    id: "c-agent-2",
    name: "وسيط الحي",
    phone: "+966503333002",
    role: "agent",
  },
];

export const seedMessages: IncomingMessage[] = [
  {
    id: "msg-1001",
    channel: "whatsapp",
    mediaKind: "text",
    from: directory[0],
    body: "عندي شقة للبيع في حي النرجس، ٤ غرف، السعر مليون و٢٠٠.",
    receivedAt: "2026-08-02T09:15:00.000Z",
    listing: {
      neighborhood: "النرجس",
      city: "الرياض",
      intent: "sale",
      propertyType: "شقة",
      priceHint: "1,200,000",
      roomsHint: "4",
    },
    status: "routed",
    routedTo: "agent",
    routedContactId: "c-agent-1",
    copyCount: 1,
  },
  {
    id: "msg-1002",
    channel: "whatsapp",
    mediaKind: "image",
    from: directory[2],
    body: "أبي شقة للإيجار قريبة من المدارس في الياسمين.",
    receivedAt: "2026-08-02T10:40:00.000Z",
    listing: {
      neighborhood: "الياسمين",
      city: "الرياض",
      intent: "rent",
      propertyType: "شقة",
    },
    mediaUrl: "/media/sample-listing.svg",
    status: "routed",
    routedTo: "agent",
    routedContactId: "c-agent-2",
    copyCount: 1,
    notes: "تعاون وسائط: صورة → إدراج على الموقع ثم متابعة واتساب.",
  },
  {
    id: "msg-1003",
    channel: "whatsapp",
    mediaKind: "text",
    from: directory[3],
    body: "هل عندكم شقق للبيع في النرجس ٤ غرف؟",
    receivedAt: "2026-08-02T11:05:00.000Z",
    listing: {
      neighborhood: "النرجس",
      city: "الرياض",
      intent: "sale",
      propertyType: "شقة",
    },
    status: "duplicate_closed",
    duplicateOfId: "msg-1001",
    autoReply:
      "شكراً لتواصلك. يوجد لدينا عرض مشابه في نفس الحي، وسنوافيك بالتفاصيل قريباً.",
    copyCount: 2,
  },
  {
    id: "msg-1004",
    channel: "instagram",
    mediaKind: "audio",
    from: directory[1],
    body: "رسالة صوتية: فيلا للإيجار بحي الملقا مع مسبح.",
    receivedAt: "2026-08-03T07:20:00.000Z",
    listing: {
      neighborhood: "الملقا",
      city: "الرياض",
      intent: "rent",
      propertyType: "فيلا",
    },
    status: "listed",
    copyCount: 1,
    notes: "الوسائط الصوتية تُحوَّل لمتابعة واتساب مع الوسيط.",
  },
  {
    id: "msg-1005",
    channel: "website",
    mediaKind: "document",
    from: directory[4],
    body: "أرفقت صك وصورة للعقار في حي العارض — للتواصل مع المالك.",
    receivedAt: "2026-08-03T08:10:00.000Z",
    listing: {
      neighborhood: "العارض",
      city: "الرياض",
      intent: "sale",
      propertyType: "أرض",
    },
    status: "new",
    copyCount: 0,
  },
];
