/** Live acceptance: only iaqar-ai-staging + isolated preview; all temporary users/offices cleaned. */
import {chromium,expect} from '@playwright/test';import {initializeApp,cert} from 'firebase-admin/app';import {getAuth} from 'firebase-admin/auth';import {getFirestore} from 'firebase-admin/firestore';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {parseFirebaseServiceAccountJson} from '../staging-credentials.mjs';
const origin=String(process.env.PREVIEW_URL||'').replace(/\/$/,'');const worker=String(process.env.PREVIEW_WORKER_URL||'').replace(/\/$/,'');
if(!/^https:\/\/iaqar-ai-staging--office-os-preview-[a-z0-9]+\.web\.app$/.test(origin)||worker!=='https://iaqar-intake-os-preview.iaqar-ai.workers.dev')throw new Error('Refusing targets outside isolated Staging preview');
const {serviceAccount}=parseFirebaseServiceAccountJson(process.env.FIREBASE_SERVICE_ACCOUNT_JSON,'iaqar-ai-staging');if(serviceAccount.project_id!=='iaqar-ai-staging')throw new Error('Staging credential required');
initializeApp({credential:cert(serviceAccount),projectId:'iaqar-ai-staging'});const auth=getAuth();const db=getFirestore();const run=crypto.randomBytes(6).toString('hex');const offices=[];const users=[];const checks=[];const out=process.env.OUT_DIR||'/tmp/marketing-live';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch();const report={environment:'live Firebase/Worker Staging preview',origin,worker,checks,externalProvidersTested:false};
try {
 const health=await (await fetch(worker+'/health')).json();assert.equal(health.deploymentEnvironment,'staging');assert.equal(health.projectId,'iaqar-ai-staging');assert.equal(health.backendReady,true);checks.push('Staging health');
 for(const suffix of ['a','b']) {
  const id=`qa-marketing-${run}-${suffix}`;const uid=`qa-marketing-user-${run}-${suffix}`;assert.ok(!(await db.doc('offices/'+id).get()).exists);await auth.createUser({uid});users.push(uid);
  const office={officeId:id,officeName:suffix==='a'?'مكتب الاختبار الأول':'مكتب الاختبار الثاني',ownerUid:uid,active:true,isTestFixture:true,publicSlug:id,city:'المدينة المنورة',phone:'0500000000',specialties:['sale','rent'],platformOpportunityOnboardingAckAt:new Date()};
  await db.doc('offices/'+id).set(office);offices.push(id);await db.doc('publicOffices/'+id).set(office);await db.doc(`offices/${id}/members/${uid}`).set({uid,active:true,role:'owner'});
  const context=await browser.newContext({viewport:{width:390,height:844},locale:'ar-SA',acceptDownloads:true});const p=await context.newPage();await p.goto(origin+'/?office='+id+'#/tools/marketing');await p.waitForFunction(()=>Boolean(window.firebase?.apps?.length));const token=await auth.createCustomToken(uid);await p.evaluate(async token=>{await window.firebase.auth().signInWithCustomToken(token);},token);await p.reload();await expect(p.getByRole('button',{name:'تجهيز الحملة',exact:true}).first()).toBeVisible({timeout:30000});await p.getByRole('button',{name:'تجهيز الحملة',exact:true}).first().click();await expect(p.locator('.os-marketing-preview')).toHaveJSProperty('width',1080);await expect(p.locator('.os-marketing-studio p.os-error')).toHaveText('');
  await p.locator('[data-marketing-save]').click();await expect(p.getByRole('button',{name:'فتح وتعديل',exact:true})).toHaveCount(1);await p.locator('[data-marketing-approve]').click();await expect(p.getByText('معتمد — جاهز للمشاركة',{exact:true})).toBeVisible();const download=p.waitForEvent('download');await p.locator('[data-marketing-download]').click();const file=path.join(out,id+'.png');await (await download).saveAs(file);const bytes=fs.readFileSync(file);assert.equal(bytes.readUInt32BE(16),1080);assert.equal(bytes.readUInt32BE(20),1080);await p.screenshot({path:path.join(out,id+'-screen.png'),fullPage:true});
  checks.push('live save, approval, PNG and mobile '+suffix);
  const forbidden=await p.evaluate(async({worker,other})=>{const token=await firebase.auth().currentUser.getIdToken();const r=await fetch(worker+'/os/marketing',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify({action:'load',officeId:other})});return r.status;},{worker,other:suffix==='b'?offices[0]:'no-access-office'});assert.ok(forbidden===403||forbidden===404);checks.push('server cross-office access denied '+suffix);await context.close();
 }
}finally{
 await browser.close();for(const id of offices){await db.recursiveDelete(db.doc('offices/'+id));await db.doc('publicOffices/'+id).delete();}for(const uid of users)await auth.deleteUser(uid);report.cleanedUp=true;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
}
console.log(`Live marketing checks passed: ${checks.length}; temporary test data cleaned`);
